[workspace]
resolver = "2"
members = [
    "lib",
    "crates/diff-test",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["TinyuengKwan <kwantinyueng@gmail.com>"]

[workspace.dependencies]
ckb-vm = { git = "https://github.com/nervosnetwork/ckb-vm", branch = "develop" }
ckb-vm-definitions = { git = "https://github.com/nervosnetwork/ckb-vm", branch = "develop" }
ckb-vm-sail-lib = { path = "lib" }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
clap = { version = "4", features = ["derive"] }
