[package]
name = "ckb-vm-sail-ckb-runner"
description = "CKB-VM VERSION2 adapter and provisional extraction target"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
ckb-vm-sail-core = { workspace = true }
ckb-vm = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
