import argparse
from pathlib import Path
import sys
import tempfile
import unittest
from unittest.mock import patch

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import review_fixed_host_inputs as review


HEADER = '''ELF Header:
  Class: ELF64
  Data: 2's complement, little endian
  OS/ABI: UNIX - System V
  Type: DYN (Shared object file)
  Machine: Advanced Micro Devices X86-64
'''


class MetadataTests(unittest.TestCase):
    def test_dynamic_tags_and_interpreter(self):
        text = HEADER + ''' [Requesting program interpreter: /lib64/ld-linux-x86-64.so.2]
 0x01 (NEEDED) Shared library: [libc.so.6]
 0x0e (SONAME) Library soname: [libmine.so]
 0x1d (RUNPATH) Library runpath: [$ORIGIN/../lib:/fixed/lib]
'''
        result = review.parse_elf(text)
        self.assertEqual(result['needed'], ['libc.so.6'])
        self.assertEqual(result['soname'], 'libmine.so')
        self.assertEqual(result['runpath'], '$ORIGIN/../lib:/fixed/lib')
        self.assertEqual(result['interpreter'], '/lib64/ld-linux-x86-64.so.2')

    def test_static_no_dynamic_tags(self):
        result = review.parse_elf(HEADER.replace('DYN (Shared object file)', 'EXEC (Executable file)'))
        self.assertEqual(result['needed'], [])
        self.assertIsNone(result['soname'])

    def test_relocatable_object(self):
        result = review.parse_elf(HEADER.replace('DYN (Shared object file)', 'REL (Relocatable file)'))
        self.assertTrue(result['Type'].startswith('REL'))

    def test_32_bit_is_recorded_not_treated_as_compatible(self):
        result = review.parse_elf(HEADER.replace('ELF64', 'ELF32'))
        self.assertEqual(result['Class'], 'ELF32')
        self.assertNotIn('compatible', result)

    def test_missing_and_duplicate_headers_rejected(self):
        for text in [HEADER.replace('  Machine: Advanced Micro Devices X86-64\n', ''), HEADER + '  Machine: other\n']:
            with self.assertRaises(RuntimeError): review.parse_elf(text)

    def test_unknown_class_and_type_rejected(self):
        for text in [HEADER.replace('ELF64', 'ELF128'), HEADER.replace('DYN', 'UNKNOWN')]:
            with self.assertRaises(RuntimeError): review.parse_elf(text)

    def test_unparsed_needed_rejected(self):
        with self.assertRaises(RuntimeError): review.parse_elf(HEADER + ' 0x01 (NEEDED) unknown format\n')

    def test_duplicate_soname_rejected(self):
        with self.assertRaises(RuntimeError):
            review.parse_elf(HEADER + ' 0x0e (SONAME) Library soname: [x]\n' * 2)

    def test_duplicate_interpreter_rejected(self):
        with self.assertRaises(RuntimeError):
            review.parse_elf(HEADER + ' [Requesting program interpreter: /loader]\n' * 2)

    def test_cache_keeps_alternative_architectures(self):
        result = review.parse_cache("2 libs found in cache `/etc/ld.so.cache'\n\tlibc.so.6 (libc6,x86-64) => /lib/64/libc.so.6\n\tlibc.so.6 (libc6) => /lib/32/libc.so.6\nCache generated by: ldconfig\n")
        self.assertEqual(len(result), 2)
        self.assertNotEqual(result[0]['attributes'], result[1]['attributes'])

    def test_cache_count_and_unparsed_rows_rejected(self):
        for text in ["1 libs found in cache 'x'\n", "1 libs found in cache 'x'\nnot a row\n", 'unexpected format']:
            with self.assertRaises(RuntimeError): review.parse_cache(text)

    def test_download_hash_algorithms_and_mirrors(self):
        for algorithm in ['SHA256', 'SHA3_256']:
            result = review.parse_download('URL "https://one/a" https://two/b\nURL_HASH ' + algorithm + '=' + 'a' * 64 + '\n')
            self.assertEqual(result['urls'], ['https://one/a', 'https://two/b'])
            self.assertEqual(result['hash_algorithm'], algorithm)

    def test_download_unknown_hash_duplicate_or_insecure_rejected(self):
        good = 'URL https://one/a\nURL_HASH SHA256=' + 'a' * 64 + '\n'
        for text in [good + good, good.replace('SHA256', 'MD5'), good.replace('https:', 'http:')]:
            with self.assertRaises(RuntimeError): review.parse_download(text)

    def test_host_wrapper_is_recorded_but_not_executed(self):
        with tempfile.TemporaryDirectory() as folder:
            path = Path(folder) / 'wrapper'
            path.write_text('#!/bin/sh\nexit 91\n')
            path.chmod(0o755)
            with patch.object(review.subprocess, 'run', side_effect=AssertionError('must not execute')):
                self.assertEqual(review.host_identity(path)['kind'], 'script')
                with self.assertRaises(RuntimeError): review.elf_reader(path)

    def test_symlink_identity_records_actual_file(self):
        with tempfile.TemporaryDirectory() as folder:
            path = Path(folder) / 'real'
            path.write_bytes(b'\x7fELFpayload')
            link = Path(folder) / 'alias'
            link.symlink_to('real')
            result = review.host_identity(link)
            self.assertEqual(result['resolved'], str(path))
            self.assertEqual(result['sha256'], review.sha(path))

    def test_name_match_is_not_loader_resolution(self):
        meta = {'x': {'metadata': {'soname': 'libx.so', 'needed': ['libmissing.so', 'libc.so.6']}}}
        cache = [{'name': 'libc.so.6', 'path': '/host/libc.so.6', 'attributes': 'arch'}]
        result = review.name_candidates(meta, {'libs/libx.so.1': 'x'}, cache)
        self.assertEqual(result['libmissing.so']['host_cache_candidates'], [])
        self.assertEqual(result['libc.so.6']['host_cache_candidates'], cache)
        self.assertNotIn('resolved', result['libc.so.6'])

    def test_bundled_soname_does_not_require_same_filename(self):
        meta = {'x': {'metadata': {'soname': 'libx.so', 'needed': ['libx.so']}}}
        result = review.name_candidates(meta, {'libs/libx.so.1': 'x'}, [])
        self.assertEqual(result['libx.so']['bundled_name_candidates'], ['libs/libx.so.1'])

    def test_existing_output_refused_before_input_access(self):
        with tempfile.TemporaryDirectory() as folder:
            with patch.object(review, 'sha', side_effect=AssertionError('must refuse before input read')):
                with self.assertRaises(RuntimeError): review.run(argparse.Namespace(out=Path(folder)))


if __name__ == '__main__': unittest.main()
