[package]
name = "ckb-vm-sail-lib"
description = "Shared library for CKB-VM Sail formal verification"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
ckb-vm = { workspace = true }
ckb-vm-definitions = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
