#!/usr/bin/env bash
# Compile the generated theorem-prover model and compare the outcome against
# the recorded expectation.
#
# Generating a model is not evidence that the model is usable. This script is
# what separates the two, and it fails in both directions: an unexpected
# failure is a regression, and an unexpectedly successful build means the
# recorded blocker is gone and every document citing it is now wrong.
#
# Usage: ./scripts/check_proof_model.sh [lean|rust|rocq]
#
#   lean  the Sail-side model generated by scripts/generate_proof_model.sh
#   rust  the production CKB-VM path generated by scripts/generate_rust_model.sh
#   rocq  not checked yet; says so rather than passing silently

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
BACKEND="${1:-lean}"
# A blocked build fails in about a minute; a working one compiles the whole
# RV64D model, which is far slower. Override for a first successful build.
BUILD_TIMEOUT="${PROOF_BUILD_TIMEOUT:-3600}"

fail() {
    echo "ERROR: $*" >&2
    exit 1
}

case "$BACKEND" in
    lean|rust) ;;
    rocq|coq)
        cat <<'EOF'
NOT CHECKED: there is no build check for the rocq backend yet.

`proof/rocq/generated` is generation-only evidence: the definitions have been
produced from the pinned configuration, and nothing here has compiled them.
Adding this check needs a Rocq toolchain (upstream's rocq.yml uses coq 9.0.1
with coq-sail-stdpp) and is tracked in docs/semantic-gaps.md.
EOF
        exit 0
        ;;
    *) fail "backend must be lean, rust or rocq" ;;
esac

if [ "$BACKEND" = "lean" ]; then
    GENERATED="$PROJECT_DIR/proof/lean/generated/sail"
    EXPECTATION="$PROJECT_DIR/proof/lean/expected_build_status.txt"
    REGENERATE="make proof-gen BACKEND=lean"
else
    GENERATED="$PROJECT_DIR/proof/lean/generated/rust"
    EXPECTATION="$PROJECT_DIR/proof/lean/expected_rust_build_status.txt"
    REGENERATE="make proof-gen-rust"
fi

[ -d "$GENERATED" ] || fail "no generated model at $GENERATED; run $REGENERATE"
[ -f "$EXPECTATION" ] || fail "missing expectation record $EXPECTATION"
"$SCRIPT_DIR/configure_lean_project.sh" "$BACKEND"
export ELAN_TOOLCHAIN="$(tr -d '\n' < "$GENERATED/lean-toolchain")"
export LEAN_ABORT_ON_PANIC=1
ulimit -c 0

# elan installs lake outside the default PATH.
if ! command -v lake >/dev/null 2>&1; then
    if [ -x "$HOME/.elan/bin/lake" ]; then
        PATH="$HOME/.elan/bin:$PATH"
        export PATH
    else
        fail "lake not found. Install the Lean toolchain manager (elan) and the
       version in $GENERATED/lean-toolchain. Not finding a toolchain is a
       failure here: an unchecked model must not report success."
    fi
fi

read_field() {
    sed -n "s/^$1=//p" "$EXPECTATION" | head -n 1
}

EXPECTED_STATUS="$(read_field status)"
EXPECTED_MARKER="$(read_field marker)"
[ -n "$EXPECTED_STATUS" ] || fail "$EXPECTATION does not record a status"

LOG="$(mktemp)"
trap 'rm -f "$LOG"' EXIT

EXPECTED_LEAN_SAIL_REV="$(read_field lean_sail_rev)"

echo "==> Resolving the Lean support library"
# configure_lean_project.sh has pinned the toolchain and Sail dependency.
# Also check Lake's resolved revision, rather than trusting configuration alone.

(cd "$GENERATED" && lake update) >"$LOG" 2>&1 || {
    cat "$LOG" >&2
    fail "lake update failed"
}
RESOLVED_REV="$(sed -n 's/.*"rev": "\([0-9a-f]*\)".*/\1/p' "$GENERATED/lake-manifest.json" | head -n 1)"
if [ "$BACKEND" = "lean" ]; then
    echo "    lean-sail revision: ${RESOLVED_REV:-unknown}"
fi
if [ "$BACKEND" = "lean" ] && [ -n "$EXPECTED_LEAN_SAIL_REV" ] && [ "$RESOLVED_REV" != "$EXPECTED_LEAN_SAIL_REV" ]; then
    fail "lake resolved lean-sail to ${RESOLVED_REV:-nothing}, but
       $EXPECTATION pins $EXPECTED_LEAN_SAIL_REV. The model would be built
       against a different support library than the one recorded."
fi

echo "==> Building the generated $BACKEND-side Lean model (timeout ${BUILD_TIMEOUT}s)"
BUILD_STATUS=0
(cd "$GENERATED" && timeout "$BUILD_TIMEOUT" lake build) >"$LOG" 2>&1 || BUILD_STATUS=$?

if grep -qE 'PANIC|uncaught exception|Stack overflow' "$LOG"; then
    fail "compiler panic/internal failure in generated model build (including cached traces)"
fi

if [ "$BUILD_STATUS" -eq 124 ]; then
    tail -n 20 "$LOG" >&2
    fail "the build did not finish within ${BUILD_TIMEOUT}s; raise PROOF_BUILD_TIMEOUT
       to record a real outcome rather than leaving it unknown"
fi

case "$EXPECTED_STATUS" in
    ok)
        if [ "$BUILD_STATUS" -eq 0 ]; then
            echo "OK: the generated $BACKEND-side Lean model compiles, as recorded."
            exit 0
        fi
        tail -n 30 "$LOG" >&2
        fail "the generated Lean model no longer compiles, and $EXPECTATION records
       that it should. This is a regression, not a known gap."
        ;;
    blocked)
        [ -n "$EXPECTED_MARKER" ] || fail "$EXPECTATION records status=blocked without a marker"
        if [ "$BUILD_STATUS" -eq 0 ]; then
            fail "the generated Lean model now COMPILES, but $EXPECTATION still records
       it as blocked. Update that record and every document citing it --
       README.md, VERIFICATION.md and docs/semantic-gaps.md all state that the
       Lean track is blocked. A stale blocker understates what is proven."
        fi
        if grep -qF "$EXPECTED_MARKER" "$LOG"; then
            cat <<EOF
KNOWN BLOCKED: the generated $BACKEND-side Lean model does not compile.

    target: $(read_field target)
    error:  $EXPECTED_MARKER

This is the recorded state, not a new failure. The reason and what unblocking
requires are in $EXPECTATION. Generation is reproducible; the model is not
usable, and no Lean theorem can be kernel-checked against it yet.
EOF
            exit 0
        fi
        tail -n 30 "$LOG" >&2
        fail "the Lean build failed for a DIFFERENT reason than the one recorded in
       $EXPECTATION (expected to find: $EXPECTED_MARKER).
       Investigate before updating the record."
        ;;
    *)
        fail "$EXPECTATION records an unknown status '$EXPECTED_STATUS'"
        ;;
esac
