"""Read-only static host-input review for the fixed restored candidate.

Reads ELF metadata using readelf, never ldd or the inspected executable. Host
cache entries and bundled SONAMEs are name candidates, NOT loader resolution.
Exit 0 means the inventory was recorded, not host compatibility or clean-room.
"""
import argparse
from concurrent.futures import ThreadPoolExecutor
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys

import restore_fixed_inputs as restore

bundle = restore.bundle
require, sha, read = restore.require, restore.sha, restore.read
RESTORATION_SHA = 'f3ef0562b6d4be513ef2014a36084e24dc8e1feee1c23eb7f74b071a1b2b69b8'
INSTALL_SHA = 'd6c28ebc2fc9f6010aec478763a4f792bd18c5ec17b5fafc50fc3675cc5266b2'
CATALOGUE_SHA = 'b9015281f8a2c4d30aabd0b91eb6993d492b87e15eb83dcf93a8a66df8daa523'
HOST_NAMES = ('sh', 'bash', 'python3', 'git', 'make', 'cmake', 'ninja', 'cc', 'c++',
              'gcc', 'g++', 'ar', 'ld', 'ranlib', 'pkg-config', 'jq', 'z3', 'opam',
              'rustup', 'sed', 'awk', 'sort', 'head', 'sha256sum', 'tar', 'xz',
              'bzip2', 'gzip', 'patch', 'curl', 'nproc')
DOWNLOAD_FILES = {
    'gmp': 'deps/sail-riscv/CMakeLists.txt',
    'cli11': 'deps/sail-riscv/dependencies/CLI11/CMakeLists.txt',
    'jsoncons': 'deps/sail-riscv/dependencies/jsoncons/CMakeLists.txt',
    'asio': 'deps/sail-riscv/dependencies/asio/CMakeLists.txt',
}


def prefix(path):
    with Path(path).open('rb') as stream: return stream.read(4096)


def parse_elf(output):
    result = {}
    for key in ('Class', 'Data', 'OS/ABI', 'Type', 'Machine'):
        rows = re.findall(r'^\s*' + re.escape(key) + r':\s*(.+)$', output, re.M)
        require(len(rows) == 1, 'missing/duplicate ELF header: ' + key)
        result[key] = rows[0].strip()
    require(result['Class'] in ('ELF32', 'ELF64'), 'unknown ELF class')
    require(result['Type'].split()[0] in ('REL', 'EXEC', 'DYN', 'CORE'), 'unknown ELF type')
    result['needed'] = re.findall(r'\(NEEDED\)\s+Shared library: \[([^\]\n]+)\]', output)
    require(output.count('(NEEDED)') == len(result['needed']), 'unparsed NEEDED tag')
    for tag, label in [('SONAME', 'Library soname'), ('RPATH', 'Library rpath'), ('RUNPATH', 'Library runpath')]:
        values = re.findall(r'\(' + tag + r'\)\s+' + label + r': \[([^\]\n]*)\]', output)
        require(len(values) <= 1 and output.count('(' + tag + ')') == len(values), 'invalid ' + tag)
        result[tag.lower()] = values[0] if values else None
    values = re.findall(r'\[Requesting program interpreter: ([^\]\n]+)\]', output)
    require(len(values) <= 1, 'duplicate ELF interpreter')
    result['interpreter'] = values[0] if values else None
    return result


def parse_cache(output):
    rows = []
    lines = output.splitlines()
    require(lines and re.match(r'^\d+ libs found in cache ', lines[0]), 'unknown loader cache listing')
    declared = int(lines[0].split()[0])
    for line in lines[1:]:
        if not line.strip() or line.startswith('Cache generated by:'): continue
        match = re.fullmatch(r'\s+(\S+) \(([^)]+)\) => (/[^\n]+)', line)
        require(match is not None, 'unparsed loader cache entry')
        name, attributes, path = match.groups()
        rows.append({'name': name, 'attributes': attributes, 'path': path})
    require(len(rows) == declared, 'loader cache count differs')
    return rows


def parse_download(text):
    urls = re.findall(r'^\s*URL\s+(.+)$', text, re.M)
    hashes = re.findall(r'^\s*URL_HASH\s+(SHA256|SHA3_256)=([0-9a-f]{64})\s*$', text, re.M)
    require(len(urls) == len(hashes) == 1, 'unexpected download declarations')
    values = [item.strip('"') for item in urls[0].split()]
    require(values and all(value.startswith('https://') for value in values), 'unexpected download URL')
    return {'urls': values, 'hash_algorithm': hashes[0][0], 'digest': hashes[0][1]}


def host_identity(path):
    path = Path(path).absolute()
    resolved = path.resolve(strict=True)
    require(resolved.is_file(), 'host input is not a regular file')
    data = prefix(resolved)
    return {'path': str(path), 'resolved': str(resolved), 'sha256': sha(resolved),
            'bytes': resolved.stat().st_size, 'mode': resolved.stat().st_mode & 0o7777,
            'kind': 'elf' if data.startswith(b'\x7fELF') else 'script' if data.startswith(b'#!') else 'other',
            'shebang': data.split(b'\n', 1)[0].decode('utf-8', 'backslashreplace') if data.startswith(b'#!') else None}


def elf_reader(path):
    identity = host_identity(path)
    require(identity['kind'] == 'elf' and os.access(identity['resolved'], os.X_OK), 'reader is not an executable ELF')
    return identity


def name_candidates(metadata, paths, cache):
    names = {}
    for path, digest in paths.items():
        item = metadata[digest]['metadata']
        # Both are only names. A matching basename/SONAME does not establish
        # architecture, ABI, namespace, version or actual loader search order.
        for name in {Path(path).name, item['soname']} - {None}:
            names.setdefault(name, []).append(path)
    needed = sorted({name for item in metadata.values() for name in item['metadata']['needed']})
    return {name: {'bundled_name_candidates': sorted(set(names.get(name, []))),
                   'host_cache_candidates': [row for row in cache if row['name'] == name]}
            for name in needed}


def run(args):
    out = restore.new_path(args.out)
    require(sha(args.restore_report) == RESTORATION_SHA, 'unreviewed restoration report')
    receipt = read(args.restore_report)
    require(receipt['status'] == 'fixed_inputs_staged_noncanonical_full_verification_not_claimed', 'restoration not terminal staging')
    root = Path(receipt['destination'])
    require(root.resolve() == root and root.is_dir() and root != restore.CANONICAL, 'review requires restored noncanonical checkout')
    require(sha(args.install_manifest) == INSTALL_SHA, 'installation manifest differs')
    installs = bundle.load_manifest(args.install_manifest, INSTALL_SHA)
    catalogue_path = root / 'proof/lean/decoder/rebuilt-input-catalogue.json'
    require(sha(catalogue_path) == CATALOGUE_SHA, 'decoder catalogue differs')
    catalogue = read(catalogue_path)
    snapshot_path = args.restore_report.parent / 'source-capsule/source-snapshot.json'
    require(sha(snapshot_path) == receipt['source_snapshot_sha256'], 'frozen source snapshot differs')
    state = read(snapshot_path)
    with restore.isolated_process_environment():
        require(restore.source_snapshot.capture(root) == state, 'restored source differs')
    readers = {'readelf': elf_reader(args.readelf), 'ldconfig_print_cache': elf_reader(args.ldconfig_reader)}
    out.mkdir(parents=True)
    report = {'status': 'running', 'started_at': restore.stamp(), 'schema_version': 1,
              'restoration_report_sha256': RESTORATION_SHA, 'restored_checkout': str(root),
              'installation_manifest_sha256': INSTALL_SHA, 'catalogue_sha256': CATALOGUE_SHA,
              'source_snapshot_sha256': receipt['source_snapshot_sha256'], 'readers': readers,
              'sources': {str(Path(module.__file__).resolve()): sha(Path(module.__file__))
                          for module in [sys.modules[__name__], restore, bundle,
                                         restore.source_snapshot, restore.source_snapshot.baseline]},
              'commands': [], 'clean_room_closed': False, 'week6_closed': False, 'release_claimed': False,
              'host_closure_complete': False, 'loader_resolution_proved': False,
              'inspected_tools_executed': False, 'host_packages_installed': False,
              'network_downloads_performed': False, 'proof_chain_executed': False,
              'os_sandboxed': False, 'operational_toolchain_verified': False}
    def save(): (out / 'report.json').write_text(json.dumps(report, indent=2, sort_keys=True) + '\n')
    def command(argv, log):
        proc = subprocess.run(argv, env={'PATH': '/usr/bin:/bin', 'LC_ALL': 'C'}, cwd=out,
                              stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=60)
        (out / (log + '.stdout')).write_bytes(proc.stdout)
        (out / (log + '.stderr')).write_bytes(proc.stderr)
        row = {'argv': argv, 'exit_code': proc.returncode,
               'stdout': log + '.stdout', 'stdout_sha256': sha(out / (log + '.stdout')),
               'stderr': log + '.stderr', 'stderr_sha256': sha(out / (log + '.stderr'))}
        require(proc.returncode == 0 and not proc.stderr, 'metadata reader failed: ' + log)
        return proc.stdout.decode(), row
    save()
    try:
        cache_before = host_identity('/etc/ld.so.cache')
        cache_text, row = command([readers['ldconfig_print_cache']['resolved'], '-p'], 'host-cache')
        report['commands'].append(row)
        cache = parse_cache(cache_text)
        report['host_cache_file'] = cache_before
        report['host_cache_rows'] = len(cache)
        entries = dict(installs['entries'])
        for name, identity in catalogue['files'].items():
            target = 'artifacts/decoder-inputs/rebuilt-v2/payload/' + bundle.safe_name(name)
            require(target not in entries, 'overlapping decoder/installation input')
            entries[target] = {'kind': 'file', **identity}
        paths, samples, shebangs = {}, {}, {}
        for name, expected in entries.items():
            path = root / name
            require(bundle.identity(path) == expected, 'declared installation input drift: ' + name)
            if expected['kind'] != 'file': continue
            data = prefix(path)
            if data.startswith(b'\x7fELF'):
                digest = expected['sha256']
                paths[name] = digest
                samples.setdefault(digest, path)
            elif data.startswith(b'#!'):
                shebangs[name] = {'line': data.split(b'\n', 1)[0].decode('utf-8', 'backslashreplace'),
                                  'executable_bit': bool(expected['mode'] & 0o111)}
        report['declared_entries_checked'] = len(entries)
        report['declared_regular_files_checked'] = sum(row['kind'] == 'file' for row in entries.values())
        report['script_shebangs'] = shebangs
        print('Declared inputs checked; inspecting ' + str(len(samples)) + ' unique ELF files', flush=True)
        def inspect(pair):
            digest, path = pair
            text, command_row = command([readers['readelf']['resolved'], '-W', '-h', '-l', '-d', str(path)], 'elf-' + digest)
            require(sha(path) == digest, 'ELF changed during inspection')
            return digest, {'sample_path': str(path.relative_to(root)), 'metadata': parse_elf(text), 'command': command_row}
        with ThreadPoolExecutor(max_workers=4) as pool:
            metadata = dict(pool.map(inspect, sorted(samples.items())))
        report['elf_paths'] = paths
        report['elf_metadata_by_sha256'] = metadata
        candidates = name_candidates(metadata, paths, cache)
        report['needed_name_candidates'] = candidates
        report['names_without_candidate'] = [name for name, row in candidates.items()
                                           if not row['bundled_name_candidates'] and not row['host_cache_candidates']]
        host_paths = sorted({row['path'] for item in candidates.values() for row in item['host_cache_candidates']} |
                            {item['metadata']['interpreter'] for item in metadata.values() if item['metadata']['interpreter']})
        report['host_library_and_interpreter_files'] = {
            path: host_identity(path) if Path(path).exists() else {'path': path, 'missing': True} for path in host_paths}
        report['host_command_files'] = {}
        for name in HOST_NAMES:
            path = shutil.which(name, path='/usr/bin:/bin')
            report['host_command_files'][name] = host_identity(path) if path else {'missing': True}
        report['cold_build_downloads'] = {}
        for name, relative in DOWNLOAD_FILES.items():
            path = root / relative
            report['cold_build_downloads'][name] = {'source': relative, 'source_sha256': sha(path),
                                                   **parse_download(path.read_text())}
        report['host_os_release'] = host_identity('/etc/os-release')
        report['host_os_release_text'] = Path('/etc/os-release').read_text()
        report['limitations'] = [
            'Static declared installation and decoder payload inputs only; not every checkout/host file.',
            'SONAME/basename/cache candidates are not selected runtime libraries or ABI/version compatibility.',
            'Host candidate libraries are hashed, not recursively resolved; dlopen/plugin/data accesses are not closed.',
            'Scripts are inventoried by shebang only, never executed; env/shebang interpreter selection is not proved.',
            'Representative host commands are identified without running version commands or compile/link probes.',
            'Static archives, headers, C/C++ sysroots and Cargo registry caches are not a complete build-input closure.',
            'Four pinned CMake downloads are declarations only; network availability/content or offline population is untested.',
            'Existing absolute installation report paths still bind canonical deployment; no path relocation adopted.',
            'Host observations occurred after the documented LXD-wrapper incident; no unchanged-host claim.',
        ]
        save()
        # Bookend all declared bytes, external observed files and the data-reader
        # executables. This does not execute the candidate or mutate host state.
        for name, expected in entries.items(): require(bundle.identity(root / name) == expected, 'input drift after inspection')
        for row in [*readers.values(), *report['host_library_and_interpreter_files'].values(),
                    *report['host_command_files'].values(), cache_before, report['host_os_release']]:
            if row.get('missing'): continue
            require(host_identity(row['path']) == row, 'observed host input drift: ' + row['path'])
        with restore.isolated_process_environment():
            require(restore.source_snapshot.capture(root) == state, 'source drift after inspection')
        require(sha(args.restore_report) == RESTORATION_SHA and sha(args.install_manifest) == INSTALL_SHA and
                all(sha(Path(name)) == digest for name, digest in report['sources'].items()), 'review input/code drift')
        report['status'] = 'static_host_input_inventory_recorded_not_environment_acceptance'
    except (Exception, KeyboardInterrupt) as error:
        report.update(status='failed', error=str(error), error_type=type(error).__name__)
    report['finished_at'] = restore.stamp()
    save()
    print(json.dumps({'status': report['status'], 'report': str(out / 'report.json'), 'error': report.get('error')}), flush=True)
    return 0 if report['status'] == 'static_host_input_inventory_recorded_not_environment_acceptance' else 1


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--restore-report', type=Path, required=True)
    parser.add_argument('--install-manifest', type=Path, required=True)
    parser.add_argument('--out', type=Path, required=True)
    parser.add_argument('--readelf', type=Path, default=Path('/usr/bin/readelf'))
    parser.add_argument('--ldconfig-reader', type=Path, default=Path('/usr/sbin/ldconfig.real'))
    args = parser.parse_args()
    try: return run(args)
    except (Exception, KeyboardInterrupt) as error:
        print('ERROR: ' + str(error), file=sys.stderr)
        return 1


if __name__ == '__main__': raise SystemExit(main())
